DRAFT: Cached compares, df view updates
Oxen-AI/oxen-archive pull request #222
Opened 2023-11-29 19:35 UTC by benartuso

2023-12-04 16:44 UTC, benartuso commented
@lewazo

2023-12-05 17:03 UTC, gschoeni requested changes

2023-12-05 17:03 UTC, gschoeni commented on src/lib/src/view/compare.rs
> +                "/compare/df/{}/{}/{}..{}",
@benartuso let's update all these to /data_frame as the old /df is depreciated. Sorry for the confusion.

2023-12-05 17:03 UTC, gschoeni commented on src/server/src/routes.rs
> +            "/{namespace}/{repo_name}/compare/df/{compare_id}/{path}/{base_head:.*}",
Update these to /data_frame

2023-12-05 17:55 UTC, benartuso commented on src/lib/src/view/compare.rs
> +                "/compare/df/{}/{}/{}..{}",
👍

2023-12-05 17:55 UTC, benartuso commented on src/server/src/routes.rs
> +            "/{namespace}/{repo_name}/compare/df/{compare_id}/{path}/{base_head:.*}",
👍

2023-12-06 01:49 UTC, merged