Refactor/rm fix
Oxen-AI/oxen-archive pull request #409
Opened 2024-09-16 18:41 UTC by rpschoenburg

Fixed errant print statements + unhandled errors

2024-09-16 21:05 UTC, jcelliott requested changes

2024-09-16 21:05 UTC, jcelliott commented on src/lib/src/core/v0_19_0/rm.rs
> +                    log::debug!("Err: {err:?}");
I think this would be cleaner using the `?` operator:
```
remove_dir(repo, &maybe_head_commit, path.clone())?;
total += dir_stats;
```

2024-09-16 21:05 UTC, jcelliott commented on src/lib/src/core/v0_19_0/rm.rs
> +                    log::debug!("Err: {err:?}");
Same thing here. You don't need the match statement if you're just going to return the error.

2024-09-16 21:05 UTC, jcelliott commented on src/lib/src/core/v0_19_0/rm.rs
> +                    match remove_staged_dir(repo, &path, staged_db) {
What behavior do we want here? If errors coming from `remove_staged_dir` actually aren't errors, we shouldn't be returning a Result with possible errors from that function.

2024-09-17 19:33 UTC, rpschoenburg commented
All bugs with this appear to be fixed. It's working fine on Windows. Also, not seeing any warnings except unused variable

2024-09-17 21:38 UTC, merged