move bulk updates to sql layer
Oxen-AI/oxen-archive pull request #463
Opened 2024-11-07 20:34 UTC by EloyMartinez

2024-11-11 18:28 UTC, gschoeni requested changes
Can we add a unit test for inserting embeddings as well for future proofing?

2024-11-11 23:54 UTC, gschoeni reviewed
Just one println! cleanup then it looks good!

2024-11-11 23:54 UTC, gschoeni commented on src/server/src/controllers/workspaces/data_frames/columns.rs
> +    println!("bonjour bonjour");
Bonjour 👋

2024-11-12 00:02 UTC, EloyMartinez commented on src/server/src/controllers/workspaces/data_frames/columns.rs
> +    println!("bonjour bonjour");
bonjour ça va

2024-11-12 00:02 UTC, EloyMartinez commented on src/server/src/controllers/workspaces/data_frames/columns.rs
> +    println!("bonjour bonjour");
done!!!!

2024-11-12 00:03 UTC, merged